spring:
  profiles:
    action: dev

---
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
server:
  port: 8201
eureka:
  client:
   service-url:
     defauleZone: http://eureka7001.com:7001/eureka/

---
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
server:
  port: 8202
eureka:
  client:
   service-url:
     defauleZone: http://eureka7001.com:7001/eureka/